---
title: "AEX Amsterdam Stock Index"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    horizontal_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(rvest)
library(treemap)
library(d3treeR)
library(quantmod)
library(dygraphs)
library(DT)
library(tools) #try to remove with own function
library(plotly)


date_converter <- function(date) {
  months <- c("January","February","March","April","May","June","July","August","September", "October","November","December")
  converted_date <- paste(months[as.numeric(substring(date, 6, 7))],paste0(substring(date, 9, 10),","), substring(date,1,4))
  return(converted_date)
}


style_widget <- function(hw=NULL, style="", addl_selector="") {
  stopifnot(!is.null(hw), inherits(hw, "htmlwidget"))
  
  # use current id of htmlwidget if already specified
  elementId <- hw$elementId
  if(is.null(elementId)) {
    # borrow htmlwidgets unique id creator
    elementId <- sprintf(
      'htmlwidget-%s',
      htmlwidgets:::createWidgetId()
    )
    hw$elementId <- elementId
  }
  
  htmlwidgets::prependContent(
    hw,
    htmltools::tags$style(
      sprintf(
        "#%s %s {%s}",
        elementId,
        addl_selector,
        style
      )
    )
  )
}

```



```{r}

#Prices df------------------------------------------
aex <- read_html("https://finance.yahoo.com/quote/%5EAEX/components/")

aex <- aex %>% 
  html_nodes("table") %>% 
  html_table()

aex <- aex[[1]]

names(aex) <- tolower(names(aex))
names(aex) <- sub(" ","_", names(aex))
aex$symbol <- sub(".AS", "", aex$symbol)

names(aex)[5] <- "percent_change"

aex$percent_change <- parse_number(aex$percent_change)
aex$volume <- parse_number(aex$volume)

#Company info df------------------------------------
company_info <- read_html("https://en.wikipedia.org/wiki/AEX_index")

company_info <- company_info  %>% 
  html_nodes("table") %>% 
  html_table(fill=TRUE)

company_info <- company_info[[2]]

names(company_info) <- tolower(names(company_info))
names(company_info) <- sub(" ","_", names(company_info))
company_info <- rename(company_info, index_weighting = `index_weighting (%)`, symbol = ticker_symbol)
company_info$icb_sector<- toTitleCase(company_info$icb_sector)
company_info <- company_info %>% 
  select(-company)

aex <- left_join(aex, company_info, by="symbol")
rm(company_info)

aex <- aex %>% 
  mutate(
    symbol_percent = paste0(symbol," ", percent_change,"%"),
    names_size=ifelse(index_weighting<2.5,"Smaller Cap",symbol_percent))



#AEX time seris-------------------------------------
invisible(getSymbols('^AEX'))

```




```{r}
#Subsetting
fivedays <- paste0(as.character(Sys.Date()-5),"/",as.character(Sys.Date()))
sevendays <- paste0(as.character(Sys.Date()-5),"/",as.character(Sys.Date()))

current_month <- paste0(as.character(cut(Sys.Date(), "month")),"/",as.character(Sys.Date()))

last30days <- paste0(as.character(Sys.Date()-30),"/",as.character(Sys.Date()))

closing_prices <- AEX$AEX.Close
closing_2019 <- AEX$AEX.Close["2019"]
closing_fivedays <- AEX$AEX.Close[fivedays]
volume_fivedays <- AEX$AEX.Volume[fivedays]

closing_last30days <- AEX$AEX.Close[last30days]
volume_last30days <- AEX$AEX.Volume[last30days]


aex_dt <- aex %>% 
  select(symbol,company_name,last_price,percent_change,index_weighting, icb_sector)
```



```{r}
#valuebox data


aex_close <- last(AEX$AEX.Close)[[1]]
aex_open<- last(AEX$AEX.Open)[[1]]
aex_close_before <- last(AEX$AEX.Close, n=2)[[1]]

aex_close_round <- round(last(AEX$AEX.Close)[[1]], digits = 2)
aex_open_round<- round(last(AEX$AEX.Open)[[1]],digits = 2)
aex_high_round <- round(last(AEX$AEX.High)[[1]], digits = 2)
aex_low_round <- round(last(AEX$AEX.Low)[[1]], digits = 2)


aex_percent_open_today <- paste0(round((aex_close-aex_open)/aex_open*100, digits=2),"%")
aex_percent_close_yesterday <- paste0(round((aex_close-aex_close_before)/aex_close_before*100, digits=2),"%")


```

Column {data-width=170}
-------------------------------------
    
### Today's Index Closing Price
    
```{r}
valueBox(aex_close_round, icon = "analytics")
```

### Change from Yesterday's Close
    
```{r}
valueBox(aex_percent_close_yesterday, icon = "analytics", color = if ((aex_close-aex_close_before)/aex_close_before>0) {
  "#00ba38"
} else if ((aex_close-aex_close_before)/aex_close_before<0){
  "#f8766d"
} else {
  "primary"
} )


```

### Change from Today's Open
    
```{r}
valueBox(aex_percent_open_today, icon = "analytics",color = if ((aex_close-aex_open)/aex_open>0) {
  "#00ba38"
} else if ((aex_close-aex_open)/aex_open<0) {
  "#f8766d"
} else {
  "primary"
} )
```

### Today's Open
    
```{r}
valueBox(aex_open_round, icon = "analytics")
```

### Today's High 
    
```{r}
valueBox(aex_high_round, icon = "analytics")
```


### Today's Low 
    
```{r}
valueBox(aex_low_round, icon = "analytics")
```


Column 
-------------------------------------
    
### Daily Performance by Index Component
    
```{r}
pdf(NULL)

tree1<- treemap(
  dtf= aex,
  index =c("names_size","symbol_percent"),
  vSize="index_weighting",
  vColor="percent_change",
  type="value",
  fun.aggregate="weighted.mean",
  palette =c("#590000","#b50a00","white","#00ba0c", "#035900"),
  mapping=c(-5, 0, 5),
  position.legend = "none"
)

style_widget(
  d3tree3(tree1, rootname ="AEX"),
  addl_selector="text",
  style="font-family:Ubuntu; font-size:15px;"
)
```
   
Column {.tabset}
-------------------------------------
   
### Top Daily Gainers

```{r}
datatable(aex_dt,
          extensions = 'Buttons',
          options=list(order = list(list(3, 'desc')),
                       paging = FALSE,
                       dom = 'Bfrtip',
                       buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                       info = FALSE),
          colnames = c("Ticker", "Company", "Last Price", "Percent Change","Index Weight","ICB Sector"),
          fillContainer = TRUE,
          rownames = FALSE,
          caption = htmltools::tags$caption(
            style = 'caption-side: bottom; text-align: center;',
            'Data source: finance.yahoo.com'))
```   
 
### Top Daily Losers
    
```{r}
datatable(aex_dt,
          extensions = 'Buttons',
          options=list(order = list(list(3, 'asc')),
                       paging = FALSE,
                       dom = 'Bfrtip',
                       buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                       info = FALSE),
          colnames = c("Ticker", "Company", "Last Price", "Percent Change","Index Weight", "ICB Sector"),
          fillContainer = TRUE,
          rownames = FALSE,
          caption = htmltools::tags$caption(
            style = 'caption-side: bottom; text-align: center;',
            'Data source: finance.yahoo.com'))
```


### Ranking Plot
```{r fig.height=6, fig.width=5}
aex <- aex %>% 
  mutate(daily_gain_loss = ifelse(percent_change>0, "gain", "loss"))

ggplot(aex, aes(reorder(symbol,percent_change, FUN = "identity"), percent_change))+
  geom_bar(stat="identity", aes(fill=daily_gain_loss), show.legend = FALSE)+
  geom_text(aes(label=paste0(percent_change,"%")),
              hjust = ifelse(aex$percent_change>0,-0.1,1.1)) +
  scale_fill_manual(values = c("#00ba38","#f8766d")) + 
  scale_y_continuous(limits = c(min(aex$percent_change)-0.25, max(aex$percent_change)+0.25))+
  coord_flip()+
  theme_minimal()+
  theme(
    panel.grid.major.x =element_blank(),
    panel.grid.minor.x =element_blank(),
    axis.title.x=element_blank(),
    axis.title.y=element_blank(),
    axis.text.x=element_blank()
  )
```

### Historical Index Data


```{r}
options(scipen=999)


dygraph(AEX, main="AEX") %>%
  dyRangeSelector() %>%
  dyCandlestick() %>% 
  dySeries("AEX.Close", axis = 'y2') %>% 
  dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.3)
```



